---
- name: Retrieve Cisco IOS running configuration
  inventories: Cisco Network Switches          # This should match a host or group in AAP inventory
  gather_facts: no
  connection: network_cli       # Use network_cli since AAP passes connection method
  tasks:
    - name: Get running config from Cisco IOS device
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config_output

    - name: Display running configuration
      debug:
        var: running_config_output.stdout[0]