---
- name: Retrieve running config from Cisco switch
  hosts:
    roseland:
      ros-dndesktop-sw01:
        ansible_host: 10.252.15.221
        ansible_become: 'yes'
        ansible_become_method: enable
        ansible_user: netadmin
      ros-access-sw01:
        ansible_host: 10.252.15.10
        ansible_become: 'yes'
        ansible_become_method: enable
        ansible_user: netadmin
      ros-access-sw02:
        ansible_host: 10.252.15.11
        ansible_become: 'yes'
        ansible_become_method: enable
        ansible_user: netadmin
      ros-access-sw03:
        ansible_host: 10.252.15.12
        ansible_become: 'yes'
        ansible_become_method: enable
        ansible_user: netadmin
      ros-access-sw04:
        ansible_host: 10.252.15.13
        ansible_become: 'yes'
        ansible_become_method: enable
        ansible_user: netadmin
    Christiansburg:
      chr-access-sw1:
        ansible_host: 10.44.5.10
        ansible_become: 'yes'
        ansible_become_method: enable
        ansible_user: netadmin
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{my_username}}"
    ansible_password: "{{my_password}}"
    ansible_become: yes
    ansible_become_method: enable
    #ansible_become_password: your_enable_password
  tasks:

     - name: Get the running configuration
       cisco.ios.ios_command:
         commands:
           - show running-config
       register: running_config_output



     - name: Display running configuration
       debug:
        var: running_config_output.stdout[0]