---
- name: Retrieve running config from Cisco IOS switches
  gather_facts: no  # typically not needed for network devices
  hosts: Roseland_Switches
  connection: network_cli
  vars:
    ansible_network_os: ios
  tasks:
    - name: Get running configuration from Cisco switch with cli_command
      ansible.netcommon.cli_command:
        command: show running-config
      register: running_config_output

    - name: Show running config output
      debug:
        var: run_cfg.stdout_lines