---
- name: Retrieve running config from Cisco switch
  hosts: "{{my_hosts}}"
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{my_username}}"
    ansible_password: "{{my_password}}"
    ansible_become: yes
    ansible_become_method: enable
    #ansible_become_password: your_enable_password
  tasks:

    # - name: Get the running configuration
    #   cisco.ios.ios_command:
    #     commands:
    #       - show running-config
    #   register: running_config_output

    - name: Get the running configuration
      cisco.ios.config:
      register: running_config_output

    - name: Display running configuration
      debug:
        var: running_config_output.stdout[0]